const fs = require('fs');
let str = fs.readFileSync('src/calldata.ts', 'utf8');

str = str.replace(
  'import { applyFieldFormats } from "./fields.js";',
  'import { applyFieldFormats } from "./fields.js";\nimport { resolveTopLevelSwitch } from "./interaction.js";\nimport type { DescriptorFormatSpec } from "./types.js";'
);

str = str.replace(
  'export async function formatCalldata(\n  tx: Transaction,\n  descriptor: Descriptor,\n  externalDataProvider?: ExternalDataProvider,\n  formatEmbeddedCalldata?: FormatCalldata,\n): Promise<DisplayModel> {',
  'export async function formatCalldata(\n  tx: Transaction,\n  descriptor: Descriptor,\n  resolveCalldataDescriptor: (chainId: number, to: string) => Promise<{ descriptor?: Descriptor; warning?: Warning }>,\n  externalDataProvider?: ExternalDataProvider,\n  formatEmbeddedCalldata?: FormatCalldata,\n): Promise<DisplayModel> {'
);

str = str.replace(
  '  const { inputs, spec: format } = match;\n  let decoded: DecodedArguments;\n  try {\n    decoded = decodeArguments(inputs, calldata);\n  } catch {\n    return {\n      rawCalldataFallback: rawPreviewFromCalldata(selector, calldata),\n      warnings: [\n        warn(\n          "CALLDATA_DECODE_ERROR",\n          `Failed to decode calldata for selector ${selectorHex}`,\n        ),\n      ],\n    };\n  }\n\n  const resolvePath: BaseResolvePath = (path: string) => {\n    if (path.startsWith("@.")) return resolveTransactionPath(path, tx);\n    if (path.startsWith("$."))\n      return toArgumentValue(resolveMetadataValue(descriptor.metadata, path));\n    const key = normalizeNegativeIndices(\n      stripStructuredRootPrefix(path),\n      decoded.arrayLengths,\n    );\n    if (key === undefined) return undefined;\n    return decoded.values.get(key);\n  };\n\n  const getArrayLength = (path: string): number => {\n    const key = normalizeNegativeIndices(\n      stripStructuredRootPrefix(path),\n      decoded.arrayLengths,\n    );\n    if (key === undefined) return 0;\n    return decoded.arrayLengths.get(key) ?? 0;\n  };\n\n  const definitions = descriptor.display?.definitions ?? {};\n  const result = await applyFieldFormats(\n    format,\n    definitions,\n    resolvePath,\n    getArrayLength,\n    tx.chainId,\n    descriptor.metadata,\n    externalDataProvider,\n    formatEmbeddedCalldata,\n  );\n\n  if ("warnings" in result) {\n    return {\n      rawCalldataFallback: rawPreviewFromCalldata(selector, calldata),\n      warnings: result.warnings,\n    };\n  }\n\n  const warnings: Warning[] = [];\n  let interpolatedIntent: string | undefined;\n  if (format.interpolatedIntent) {\n    try {\n      interpolatedIntent = interpolateTemplate(\n        format.interpolatedIntent,\n        result.renderedValues,\n      );\n    } catch (e) {\n      warnings.push(warn("INTERPOLATION_ERROR", (e as Error).message));\n    }\n  }\n\n  const meta = descriptor.metadata;\n  return {\n    intent: format.intent,\n    interpolatedIntent,\n    fields: result.fields,\n    metadata: meta\n      ? {\n          owner: meta.owner,\n          contractName: meta.contractName,\n          info: meta.info,\n        }\n      : undefined,\n    ...(warnings.length > 0 && { warnings }),\n  };',
  '  const { inputs, spec: format } = match;\n  let decoded: DecodedArguments;\n  try {\n    decoded = decodeArguments(inputs, calldata);\n  } catch {\n    return {\n      rawCalldataFallback: rawPreviewFromCalldata(selector, calldata),\n      warnings: [\n        warn(\n          "CALLDATA_DECODE_ERROR",\n          `Failed to decode calldata for selector ${selectorHex}`,\n        ),\n      ],\n    };\n  }\n\n  if (format.switch) {\n    const switchResult = await resolveTopLevelSwitch(\n      tx,\n      descriptor,\n      format.switch,\n      decoded,\n      resolveCalldataDescriptor,\n      externalDataProvider,\n      formatEmbeddedCalldata\n    );\n    return {\n      ...switchResult,\n      ...(switchResult.warnings ? { rawCalldataFallback: rawPreviewFromCalldata(selector, calldata) } : {})\n    };\n  }\n\n  const result = await renderFormat(format, decoded, tx, descriptor, externalDataProvider, formatEmbeddedCalldata);\n  if (result.warnings) {\n    return {\n      ...result,\n      rawCalldataFallback: rawPreviewFromCalldata(selector, calldata),\n    };\n  }\n  return result;'
);

str += '\n\nexport async function renderFormat(\n  format: DescriptorFormatSpec,\n  decoded: DecodedArguments,\n  tx: Transaction,\n  descriptor: Descriptor,\n  externalDataProvider?: ExternalDataProvider,\n  formatEmbeddedCalldata?: FormatCalldata,\n): Promise<DisplayModel> {\n  const resolvePath: BaseResolvePath = (path: string) => {\n    if (path.startsWith("@.")) return resolveTransactionPath(path, tx);\n    if (path.startsWith("$."))\n      return toArgumentValue(resolveMetadataValue(descriptor.metadata, path));\n    const key = normalizeNegativeIndices(\n      stripStructuredRootPrefix(path),\n      decoded.arrayLengths,\n    );\n    if (key === undefined) return undefined;\n    return decoded.values.get(key);\n  };\n\n  const getArrayLength = (path: string): number => {\n    const key = normalizeNegativeIndices(\n      stripStructuredRootPrefix(path),\n      decoded.arrayLengths,\n    );\n    if (key === undefined) return 0;\n    return decoded.arrayLengths.get(key) ?? 0;\n  };\n\n  const definitions = descriptor.display?.definitions ?? {};\n  const result = await applyFieldFormats(\n    format,\n    definitions,\n    resolvePath,\n    getArrayLength,\n    tx.chainId,\n    descriptor.metadata,\n    externalDataProvider,\n    formatEmbeddedCalldata,\n  );\n\n  if ("warnings" in result) {\n    return {\n      warnings: result.warnings,\n    };\n  }\n\n  const warnings: Warning[] = [];\n  let interpolatedIntent: string | undefined;\n  if (format.interpolatedIntent) {\n    try {\n      interpolatedIntent = interpolateTemplate(\n        format.interpolatedIntent,\n        result.renderedValues,\n      );\n    } catch (e) {\n      warnings.push(warn("INTERPOLATION_ERROR", (e as Error).message));\n    }\n  }\n\n  const meta = descriptor.metadata;\n  return {\n    intent: format.intent,\n    interpolatedIntent,\n    fields: result.fields,\n    metadata: meta\n      ? {\n          owner: meta.owner,\n          contractName: meta.contractName,\n          info: meta.info,\n        }\n      : undefined,\n    ...(warnings.length > 0 && { warnings }),\n  };\n}\n';

fs.writeFileSync('src/calldata.ts', str);
